"""Dormant execution ledger; no server registration, commands or remote transport.

Only a trusted embedding supervisor may construct this service. Identity and
generation authorization must be established before calling it. An Observation
is a supervisor assertion, not proof generated by this ledger: quiescent+fenced
means all owned work ended AND delayed delivery of this attempt cannot launch.
"""
from __future__ import annotations

import fcntl
import json
import os
import re
import sqlite3
import stat
import threading
import uuid
from contextlib import contextmanager
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Protocol


class ExecutionConflict(RuntimeError):
    """Identity, replay, generation or seal conflict; do not dispatch."""


class ExecutionBusy(RuntimeError):
    """Another ledger owner or unresolved operation prevents dispatch."""


def _identifier(value: str, *, empty=False) -> None:
    if type(value) is not str or not ((empty and value == "") or re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.:@-]{0,127}", value)):
        raise ValueError("invalid execution identifier")


@dataclass(frozen=True)
class ExecutionIdentity:
    job_id: str
    execution_id: str
    user_id: str
    tenant_id: str
    generation_id: str
    generation_epoch: int
    profile_id: str
    repository_alias: str
    task_mode: str

    def __post_init__(self):
        for key, value in asdict(self).items():
            if key != "generation_epoch":
                _identifier(value, empty=key == "tenant_id")
        if type(self.generation_epoch) is not int or not 0 <= self.generation_epoch < 2**63:
            raise ValueError("invalid generation epoch")
        if self.task_mode not in ("read_only", "modification"):
            raise ValueError("invalid task mode")


@dataclass(frozen=True)
class Claim:
    identity: ExecutionIdentity
    operation_id: str
    request_sha256: str
    attempt_id: str
    authority_id: str


@dataclass(frozen=True)
class Observation:
    claim: Claim
    state: str  # running | unknown | quiescent
    fenced: bool


@dataclass(frozen=True)
class OperationStatus:
    claim: Claim
    state: str  # unknown | running | stopped


@dataclass(frozen=True)
class ExecutionStatus:
    identity: ExecutionIdentity
    state: str  # unknown | running | open | stopped
    sealed: bool
    operations: tuple[OperationStatus, ...]


class Supervisor(Protocol):
    """Trusted, bounded callbacks. Launch is invoked at most once per claim.

    Persist/fence attempts independently of delivery order. Never report fenced
    on mere absence, PID exit, timeout, or a cancelled local request. Observe must
    be read-only; stop must be idempotent. Callbacks may read status but must not
    reenter mutations. No callback runs inside a ledger transaction.
    """

    authority_id: str

    def launch(self, claim: Claim) -> Observation | None: ...
    def observe(self, claim: Claim) -> Observation | None: ...
    def stop(self, claim: Claim) -> None: ...


def _private_file(path: Path) -> int:
    fd = os.open(path, os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW | os.O_NONBLOCK, 0o600)
    info = os.fstat(fd)
    if (not stat.S_ISREG(info.st_mode) or info.st_nlink != 1
            or info.st_uid != os.getuid() or stat.S_IMODE(info.st_mode) != 0o600):
        os.close(fd)
        raise ValueError("ledger files must be private, owned regular files")
    return fd


class ExecutionService:
    """Single-process owner of a private, durable SQLite ledger on Linux.

    advance explicitly registers an identity and seals lower epochs in the same
    owner/tenant/generation/profile/repository/mode lineage. start never advances
    a generation implicitly. Global unresolved work blocks new operation claims.
    Restart seals all executions and makes unresolved operations unknown; there
    is no replay, force-clear, expiration or tombstone deletion.
    """

    def __init__(self, directory: Path, supervisor: Supervisor):
        _identifier(supervisor.authority_id)
        directory = Path(directory).absolute()
        if directory.resolve() != directory:
            raise ValueError("ledger directory must not contain symlinks")
        directory.mkdir(mode=0o700, parents=False, exist_ok=True)
        info = directory.stat()
        if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid() or stat.S_IMODE(info.st_mode) != 0o700:
            raise ValueError("ledger directory must be private and owned")
        self._lock = threading.RLock()
        self._pid = os.getpid()
        self._closed = False
        self._callback_active = False
        self._supervisor = supervisor
        self._authority = supervisor.authority_id
        self._fd = _private_file(directory / "owner.lock")
        self._db = None
        try:
            try:
                fcntl.flock(self._fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError as error:
                raise ExecutionBusy("ledger already owned") from error
            db_path = directory / "executions.sqlite3"
            os.close(_private_file(db_path))
            for suffix in ("-journal", "-wal", "-shm"):
                sidecar = db_path.with_name(db_path.name + suffix)
                if sidecar.exists() or sidecar.is_symlink():
                    os.close(_private_file(sidecar))
            self._db = sqlite3.connect(db_path, isolation_level=None, check_same_thread=False)
            self._db.row_factory = sqlite3.Row
            self._db.execute("PRAGMA journal_mode=DELETE")
            self._db.execute("PRAGMA synchronous=FULL")
            self._db.execute("PRAGMA foreign_keys=ON")
            with self._transaction():
                self._db.execute("CREATE TABLE IF NOT EXISTS executions (execution_id TEXT PRIMARY KEY, identity TEXT NOT NULL, lineage TEXT NOT NULL, epoch INTEGER NOT NULL, sealed INTEGER NOT NULL)")
                self._db.execute("CREATE TABLE IF NOT EXISTS generations (lineage TEXT PRIMARY KEY, epoch INTEGER NOT NULL, execution_id TEXT NOT NULL)")
                self._db.execute("CREATE TABLE IF NOT EXISTS operations (execution_id TEXT NOT NULL REFERENCES executions(execution_id), operation_id TEXT NOT NULL, request_sha256 TEXT NOT NULL, attempt_id TEXT NOT NULL UNIQUE, authority_id TEXT NOT NULL, state TEXT NOT NULL, PRIMARY KEY(execution_id, operation_id))")
                self._db.execute("UPDATE executions SET sealed=1 WHERE sealed=0")
                self._db.execute("UPDATE operations SET state='unknown' WHERE state!='stopped'")
        except BaseException:
            if self._db is not None:
                self._db.close()
            os.close(self._fd)
            self._closed = True
            raise

    @contextmanager
    def _transaction(self):
        self._db.execute("BEGIN IMMEDIATE")
        try:
            yield
            self._db.execute("COMMIT")
        except BaseException:
            if self._db.in_transaction:
                self._db.execute("ROLLBACK")
            raise

    @contextmanager
    def _access(self, *, mutate=False):
        with self._lock:
            if self._closed or os.getpid() != self._pid:
                raise RuntimeError("ledger closed or inherited across fork")
            if mutate and self._callback_active:
                raise RuntimeError("supervisor cannot reenter mutations")
            yield

    def close(self) -> None:
        with self._lock:
            if self._closed:
                return
            if self._callback_active or os.getpid() != self._pid:
                raise RuntimeError("cannot close from supervisor or fork")
            self._db.close()
            os.close(self._fd)
            self._closed = True

    def _record(self, identity):
        if type(identity) is not ExecutionIdentity:
            raise ValueError("execution identity required")
        row = self._db.execute("SELECT * FROM executions WHERE execution_id=?", (identity.execution_id,)).fetchone()
        if row is not None and row["identity"] != json.dumps(asdict(identity), sort_keys=True):
            raise ExecutionConflict("execution identity mismatch")
        return row

    def _register(self, identity, *, sealed):
        row = self._record(identity)
        if row is not None:
            if sealed:
                self._db.execute("UPDATE executions SET sealed=1 WHERE execution_id=?", (identity.execution_id,))
            return
        lineage = json.dumps([identity.user_id, identity.tenant_id, identity.generation_id,
                              identity.profile_id, identity.repository_alias, identity.task_mode])
        highwater = self._db.execute("SELECT epoch FROM generations WHERE lineage=?", (lineage,)).fetchone()
        if highwater is not None and identity.generation_epoch <= highwater["epoch"]:
            raise ExecutionConflict("generation is stale or already claimed")
        self._db.execute("UPDATE executions SET sealed=1 WHERE lineage=?", (lineage,))
        self._db.execute("INSERT INTO executions VALUES (?, ?, ?, ?, ?)",
                         (identity.execution_id, json.dumps(asdict(identity), sort_keys=True), lineage,
                          identity.generation_epoch, int(sealed)))
        self._db.execute("INSERT OR REPLACE INTO generations VALUES (?, ?, ?)",
                         (lineage, identity.generation_epoch, identity.execution_id))

    def advance(self, identity: ExecutionIdentity) -> ExecutionStatus:
        """Explicit durable generation fence; does not stop or dispatch work."""
        with self._access(mutate=True):
            with self._transaction():
                self._register(identity, sealed=False)
            return self.status(identity)

    def status(self, identity: ExecutionIdentity) -> ExecutionStatus:
        """Read persisted status only. Unknown/missing is never stop proof."""
        with self._access():
            row = self._record(identity)
            if row is None:
                return ExecutionStatus(identity, "unknown", False, ())
            rows = self._db.execute("SELECT * FROM operations WHERE execution_id=? ORDER BY rowid",
                                    (identity.execution_id,)).fetchall()
            operations = tuple(OperationStatus(Claim(identity, op["operation_id"], op["request_sha256"],
                                                     op["attempt_id"], op["authority_id"]), op["state"])
                               for op in rows)
            states = {op.state for op in operations}
            state = "stopped" if row["sealed"] else "open"
            if "running" in states:
                state = "running"
            if states - {"running", "stopped"}:
                state = "unknown"
            return ExecutionStatus(identity, state, bool(row["sealed"]), operations)

    def _call(self, method, claim):
        if claim.authority_id != self._authority or self._supervisor.authority_id != self._authority:
            return None
        self._callback_active = True
        try:
            return getattr(self._supervisor, method)(claim)
        except Exception:
            # Error details may contain secrets. Ambiguity never becomes proof.
            return None
        finally:
            self._callback_active = False

    def _observe(self, claim, observation):
        state = "unknown"
        if (type(observation) is Observation and type(observation.claim) is Claim
                and observation.claim == claim and type(observation.fenced) is bool):
            if observation.state == "quiescent" and observation.fenced:
                state = "stopped"
            elif observation.state == "running":
                state = "running"
        with self._transaction():
            self._db.execute("UPDATE operations SET state=? WHERE execution_id=? AND operation_id=? AND attempt_id=? AND authority_id=? AND state!='stopped'",
                             (state, claim.identity.execution_id, claim.operation_id, claim.attempt_id, claim.authority_id))

    def start(self, identity: ExecutionIdentity, operation_id: str, request_sha256: str) -> ExecutionStatus:
        """Commit before one dispatch. Replays return status, including after seal."""
        _identifier(operation_id)
        if type(request_sha256) is not str or not re.fullmatch(r"[0-9a-f]{64}", request_sha256):
            raise ValueError("canonical request SHA-256 required")
        with self._access(mutate=True):
            with self._transaction():
                row = self._record(identity)
                if row is None:
                    raise ExecutionConflict("advance identity before dispatch")
                previous = self._db.execute("SELECT request_sha256 FROM operations WHERE execution_id=? AND operation_id=?",
                                            (identity.execution_id, operation_id)).fetchone()
                if previous is not None:
                    if previous["request_sha256"] != request_sha256:
                        raise ExecutionConflict("operation digest mismatch")
                else:
                    if row["sealed"]:
                        raise ExecutionConflict("execution is sealed")
                    if self._db.execute("SELECT 1 FROM operations WHERE state!='stopped' LIMIT 1").fetchone():
                        raise ExecutionBusy("unresolved execution")
                    count = self._db.execute("SELECT count(*) FROM operations WHERE execution_id=?", (identity.execution_id,)).fetchone()[0]
                    if count >= 64:
                        raise ExecutionConflict("execution operation limit")
                    claim = Claim(identity, operation_id, request_sha256, uuid.uuid4().hex, self._authority)
                    self._db.execute("INSERT INTO operations VALUES (?, ?, ?, ?, ?, 'unknown')",
                                     (identity.execution_id, operation_id, request_sha256, claim.attempt_id, claim.authority_id))
            if previous is None:
                self._observe(claim, self._call("launch", claim))
            return self.status(identity)

    def _reconcile(self, identity, *, stop):
        for operation in self.status(identity).operations:
            if operation.state == "stopped":
                continue
            if stop:
                self._call("stop", operation.claim)
            self._observe(operation.claim, self._call("observe", operation.claim))
        return self.status(identity)

    def stop(self, identity: ExecutionIdentity) -> ExecutionStatus:
        """Seal first, then request stop and query authority; no caller proof."""
        with self._access(mutate=True):
            with self._transaction():
                self._register(identity, sealed=True)
            return self._reconcile(identity, stop=True)

    def reconcile(self, identity: ExecutionIdentity) -> ExecutionStatus:
        """Explicitly query the configured authority without dispatching work."""
        with self._access(mutate=True):
            return self._reconcile(identity, stop=False)
